GET http://localhost:8081/users

###

GET http://localhost:8081/users/61c86aba872bbcc86f2237ed
###
POST http://localhost:8081/users
Content-Type: application/json

{  
    "name": "namewaflle",
    "password": "120H7"
}
###

DElETE http://localhost:8081/users/61c86aba872bbcc86f2237ed


### 

PATCH http://localhost:8081/users/61c86de114a957ef97e3a062
Content-Type: application/json

{  
    "name": "UpdatedWaflle"
}